apiVersion: v1
kind: ConfigMap
metadata:
  name: errorfreetext-config
  namespace: errorfreetext
data:
  SPRING_PROFILES_ACTIVE: "k8s"
  APP_YANDEX_SPELLER_BASE_URL: "https://speller.yandex.net/services/spellservice.json"
  APP_YANDEX_SPELLER_REQUEST_TIMEOUT: "5000"
  APP_SCHEDULER_FIXED_DELAY: "10000"
  APP_SCHEDULER_MAX_CONCURRENT_TASKS: "3"
  POSTGRES_DB: "errorfreetext"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"