apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: errorfreetext
  labels:
    app: postgres
    service: errorfreetext
spec:
  storageClassName: zfs-csi-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi