apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: errorfreetext
  labels:
    app: postgres
    service: errorfreetext
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  clusterIP: None