apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zfs-csi-local
provisioner: zfs.csi.openebs.io
parameters:
  fsType: zfs
  compressed: "on"
  dedup: "off"
  recordsize: "128k"
  poolname: "tank/k8s"
  shared: "yes"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer